<?php
session_start();
define('HOST','localhost');
define('PORT','3306');
define('DBNAME','DeTai');
define('USERNAME','thuan');
define('PASSWORD','123456');
define('OPTION',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
define('URL','http://'.$_SERVER['HTTP_HOST'].'/DeTai/admin');