<?php
session_start();
ob_start();
define('HOST','localhost');
define('PORT','3306');
define('DBNAME','DeTai');
define('USERNAME','root');
define('PASSWORD','');
define('OPTION',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
define('URL','http://'.$_SERVER['SERVER_NAME'].'/admin');
